//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class basepart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public basepart()
        {
            this.partassembly = new HashSet<partassembly>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int manufacturerid { get; set; }
        public int parttypeid { get; set; }
        public string image { get; set; }
        public decimal price { get; set; }
        public decimal Price 
        {
         get
            {
                return decimal.Round(price, 2);
            }
        }

        public string description;
        public virtual manufacturer manufacturer { get; set; }
        public virtual parttype parttype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partassembly> partassembly { get; set; }

        public virtual string info=> $"{id}, {name}, {price}";
        
    }
}
