//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class @case : basepart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public @case()
        {
            this.boardformfactorcase = new HashSet<boardformfactorcase>();
        }
    
        public int sizeid { get; set; }
        public int expansionslots { get; set; }
        public int fans { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boardformfactorcase> boardformfactorcase { get; set; }
        public virtual casesize casesize { get; set; }

        public override string info => $"Размер: {casesize.name}\nСлоты расширения: {expansionslots}\nКоличество вентиляторов: {fans}";
    }
}
