//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class gpu : basepart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gpu()
        {
            this.videoconnectorgpu = new HashSet<videoconnectorgpu>();
        }
    
        public int gpuinterfaceid { get; set; }
        public int chipfrequency { get; set; }
        public int videomemory { get; set; }
        public int memorybus { get; set; }
        public Nullable<int> recommendpower { get; set; }
    
        public virtual gpuinterface gpuinterface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<videoconnectorgpu> videoconnectorgpu { get; set; }

        public override string info => $"Интерфейс: {gpuinterface.name}\nВидеопамять: {videomemory}\nШина памяти: {memorybus}\nЧастота: {chipfrequency}";
    }
}
