//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Tovar
    {
        public int ID { get; set; }
        public int Order { get; set; }
        public int Tovar { get; set; }
    
        public virtual Order Order1 { get; set; }
        public virtual Tovar Tovar1 { get; set; }
    }
}
