//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class processorcooler : basepart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public processorcooler()
        {
            this.socketprocessorcooler = new HashSet<socketprocessorcooler>();
        }
    
        public int fandimensionid { get; set; }
        public int heatpipes { get; set; }
        public int minspeed { get; set; }
        public int maxspeed { get; set; }
        public double noiselevel { get; set; }
    
        public virtual fandimension fandimension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<socketprocessorcooler> socketprocessorcooler { get; set; }
        public override string info => $"Размер: {fandimension.name}\nМинимальная скорость: {minspeed}\nМаксимальная скорость: {maxspeed}\nУровень шума: {noiselevel}\nТепловые трубки: {heatpipes}";
    }
}
