//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ram : basepart
    {
        public int memorytypeid { get; set; }
        public int capacity { get; set; }
        public int count { get; set; }
        public int ghz { get; set; }
        public string timings { get; set; }
    
        public virtual memorytype memorytype { get; set; }
        public override string info => $"Тип памяти: {memorytype.name}\nОбъем: {capacity} ГБ\nКоличетсва плашек: {count}\nСкорость: {ghz}ГГЦ";
    }
}
