//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ID { get; set; }
        public int ServiceTypeID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public int MasterID { get; set; }
        public bool IsComplete { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public decimal Price { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
