//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class storagedevice : basepart
    {
        public int capacity { get; set; }
        public int storagedeviceinterfaceid { get; set; }
        public int storagedevicetypeid { get; set; }
    
        public virtual storagedeviceinterface storagedeviceinterface { get; set; }
        public virtual storagedevicetype storagedevicetype { get; set; }
        public virtual hdd hdd { get; set; }
        public virtual ssd ssd { get; set; }

        public string describe_type
        {
            get
            {
                if (storagedevicetypeid == 1)
                {
                    return $"Ресурс накопителя: {ssd.tbw} Циклов";
                }
                else 
                {
                    return $"Скорость вращения: {hdd.rotationspeed}";
                }
            }
        }
        public override string info => $"Тип: {storagedevicetype.name}\nИнтерфейс: {storagedeviceinterface}\nВместимость: {capacity} ГБ\n{describe_type}";
    }
}
